"""init schema

Revision ID: 2dddf6f43273
Revises: 
Create Date: 2026-04-14 07:54:35.666837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dddf6f43273'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('conflict_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('target_student_id', sa.String(length=32), nullable=False),
    sa.Column('site1_snapshot', sa.Text(), nullable=False),
    sa.Column('site2_snapshot', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resolution IS NULL OR resolution IN ('site1','site2','skip')", name='ck_resolution'),
    sa.ForeignKeyConstraint(['user_id'], ['users.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_events', schema=None) as batch_op:
        batch_op.create_index('ix_conflict_pending', ['user_id', 'resolution'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('site1_sid_enc', sa.BLOB(), nullable=False),
    sa.Column('site1_sid_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_expires_at', ['expires_at'], unique=False)

    op.create_table('site2_credentials',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enc_refresh_token', sa.BLOB(), nullable=False),
    sa.Column('id_token', sa.Text(), nullable=False),
    sa.Column('id_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('target_student_id', sa.String(length=32), nullable=False),
    sa.Column('score_topic', sa.Integer(), nullable=False),
    sa.Column('score_content', sa.Integer(), nullable=False),
    sa.Column('score_narrative', sa.Integer(), nullable=False),
    sa.Column('score_presentation', sa.Integer(), nullable=False),
    sa.Column('score_teamwork', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('self_note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period IN ('midterm','final')", name='ck_period'),
    sa.CheckConstraint("source IN ('local','imported_site1','imported_site2')", name='ck_source'),
    sa.CheckConstraint('score_content BETWEEN 0 AND 30', name='ck_score_content'),
    sa.CheckConstraint('score_narrative BETWEEN 0 AND 20', name='ck_score_narrative'),
    sa.CheckConstraint('score_presentation BETWEEN 0 AND 10', name='ck_score_presentation'),
    sa.CheckConstraint('score_teamwork BETWEEN 0 AND 10', name='ck_score_teamwork'),
    sa.CheckConstraint('score_topic BETWEEN 0 AND 30', name='ck_score_topic'),
    sa.ForeignKeyConstraint(['user_id'], ['users.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_lookup', ['user_id', 'period', 'target_student_id', 'submitted_at'], unique=False)

    op.create_table('targets_cache',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('target_student_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('is_self', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'period', 'target_student_id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("site IN ('site1','site2','site3')", name='ck_site'),
    sa.CheckConstraint("status IN ('pending','success','failed','skipped')", name='ck_status'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_logs_site_status', ['site', 'status'], unique=False)
        batch_op.create_index('ix_sync_logs_submission', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_logs_submission')
        batch_op.drop_index('ix_sync_logs_site_status')

    op.drop_table('sync_logs')
    op.drop_table('targets_cache')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_lookup')

    op.drop_table('submissions')
    op.drop_table('site2_credentials')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_expires_at')

    op.drop_table('sessions')
    with op.batch_alter_table('conflict_events', schema=None) as batch_op:
        batch_op.drop_index('ix_conflict_pending')

    op.drop_table('conflict_events')
    op.drop_table('users')
    # ### end Alembic commands ###
