"""add user sync flags

Revision ID: 913d641c1cb8
Revises: 2dddf6f43273
Create Date: 2026-04-14 08:46:45.158844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913d641c1cb8'
down_revision: Union[str, Sequence[str], None] = '2dddf6f43273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_site1', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('sync_site2', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('sync_site3', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sync_site3')
        batch_op.drop_column('sync_site2')
        batch_op.drop_column('sync_site1')

    # ### end Alembic commands ###
